### ISSUE TITLE
more complexity/feature completeness

### ISSUE THREAD

**Issue by matu3ba** [zhuyadong/zoop#1]
not sure, if worth the hassle to implement:

basics
- moving objects ie along functions and/or eliding copies [sounds tricky for all cases]
- union of objects
- tagged union of objects
- shared ptr
- atomics

generic stuff (doubtful if useful and would be recursive and slow), could be nice to troll on C++ generics though
- generic fn creation
- concepts as constrains on generic fn creation (or some other solution)

**Comment by zhuyadong** [comment]
@matu3ba 
One of the design principles of `zoop` is to keep it as simple as possible, providing only the necessary features, including:
- Interfaces
- Function overriding
- Conversion between interfaces and classes
- Virtual function calls
- Inheritance (initially, we didn't want to support this, but it indeed reduces a lot of repetitive code. After referring to other languages that support `OOP`, we decided to include it)
- Since inheritance is supported, destructors are also supported

The creation of `zoop` stemmed from the needs of another project of mine. I use `zoop` every day and don't feel like it's missing any features. 😉
In my view, the most important aspect of `OOP` is interfaces, and I prefer to call it interface-oriented programming. Features beyond those listed above can be implemented by new modules, but they are not suitable to be included in `zoop` because they are not related to `OOP`.

**Comment by matu3ba** [comment]
> keep it as simple as possible

Ok. I was not sure how far you wanted to go towards a minimal C++.

> interface-oriented programming

Yeah, that makes sense.

**Comment by matu3ba** [comment]
Closing, since unplanned.
